

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/c322-spring-2023/configuration-files.git
          username: ${git.username}
          password: ${git.token}
          default-label: master
server:
  port: 8071

encrypt:
  key: ${}

